### ISSUE TITLE
1.1.1+ Batch

### ISSUE THREAD

**Issue by puzrin** [jonschlinkert/remarkable#52]
- [ ] Plugins examples / tutorials #48 
- [ ] Demo synk scroll #37
- [x] CDN #33 
- [x] Advice migration to remarkable. You know where :) #34 

These tickets are the most significant to make `remarkable` "solid".
